### ISSUE TITLE
where is the demo app?

### ISSUE THREAD

**Issue by sidalihallak** [xotahal/react-native-material-ui-demo-app#1]

**Comment by xotahal** [comment]
We're working on app that uses library - will be available in play store. Unfortunately I don't have time to make this demo app right now.

**Comment by sidalihallak** [comment]
it's ok , you did a great job

**Comment by shivam17** [comment]
it is still not ready?

**Comment by xotahal** [comment]
Do you mean demo app or our product app? :) Demo app is ready and our product app is already in private beta. So, hope it'll be out soon :)

**Comment by shivam17** [comment]
The demo app.

**Comment by xotahal** [comment]
Demo app is ready. I'm still working on it, but there should be all components now ;)

**Comment by shivam17** [comment]
Actually i didnt find the link to get it up and running on my emulator.
There was no code in any of the branches on your github. Please check once
and provide me with the link to download and get it running.
