### ISSUE TITLE
iOS Build Fails: Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by joncursi** [xotahal/react-native-material-ui-demo-app#2]
```

** BUILD FAILED **


The following build commands failed:
    CompileC /Users/jcursi/Sites/joncursi/react-native-material-ui-demo-app/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by xotahal** [comment]
I'm on phone right now. So I can't check it exactly. But I had a similar
problem with build. It was because of updating xcode or Mac OS Sierra not
because of this demo app. I'll send you link how to fix it when I am on ntb.

**Comment by joncursi** [comment]
Yes, I'm on Xcode 8. Thanks!

**Comment by xotahal** [comment]
This is what worked for me ;) Try it .. https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

**Comment by jasan-s** [comment]
@joncursi did you find a solution? I'm on xcode 8.2 and i always get this error when I clone a github repo and try to run locally

**Comment by dgurns** [comment]
I'm also running into this problem with a new React Native project. React Native 0.45, xCode 8.2. Wasn't a problem with RN 0.44.

**Comment by yukkeechang** [comment]
@dgurns I'm in the same exact  situation as you..did you find a solution? :(

**Comment by ldy694** [comment]
me too, I init new  project ,It's don't run

**Comment by dgurns** [comment]
I downgraded to 0.44 and it worked again, but unfortunately I don't have a solution yet for 0.45.

**Comment by kgirma** [comment]
Try deleting your build folder in IOS project directory and rerun react-native run-ios from the command line
