### ISSUE TITLE
Android build failing with missing resource files

### ISSUE THREAD

**Issue by vrajeshkanna** [xotahal/react-native-material-ui-demo-app#23]
`Error: No resource found that matches the given name (at 'label' with value '@string/app_name')`

The whole res folder is missing under android/app/src/main

**Comment by vrajeshkanna** [comment]
I see the android/app/src/main/res added in .gitignore file. Is it done purposefully for developers to have their own app name, theme and launcher Icons? It will be difficult for the new developers to understand.

**Comment by iamjoyce** [comment]
> It will be difficult for the new developers to understand.

I agree. It's supposed to be a demo application, but I am spending bulk of my time trying to fix all the errors.

**Comment by fabianTMC** [comment]
+1 please fix. I am trying to demo this to see if I can use it but the number of issues and lack of time and lack of documentation is making this a pain.

**Comment by vrajeshkanna** [comment]
I have mistakenly closed the PR #22 . This needs to be merged yet.
