### ISSUE TITLE
Requiring unknown module "color".

### ISSUE THREAD

**Issue by zaaack** [xotahal/react-native-material-ui-demo-app#4]
Looks like there was missing two modules: `color` and `lodash.merge` in package.json

**Comment by xotahal** [comment]
You're right. The react-native-material-ui is there like submodule and npm
doesn't install its dependencies. We should specify them in the demo-app as
well. Could you make a pull request please?

**Comment by zaaack** [comment]
@xotahal Sure, my pleasure.
