### ISSUE TITLE
encounted error at stating demo app

### ISSUE THREAD

**Issue by joe-re** [xotahal/react-native-material-ui-demo-app#6]
I encountered below error after `react-native run-android`.

```
Application example has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
runApplication
    AppRegistry.js:99
__callFunction
    MessageQueue.js:236
<unknown>
    MessageQueue.js:108
guard
    MessageQueue.js:46
callFunctionReturnFlushedQueue
    MessageQueue.js:107
```

![image](https://cloud.githubusercontent.com/assets/4954534/21260981/16d5e2f4-c3cc-11e6-9916-1d1285723926.png)

Do you know this error cause?

If there is any necessary other information, I will present it so please tell me.

**Comment by Steviey** [comment]
+1

**Comment by salomaojr** [comment]
Problem solved!

Another process of react-native is running. Locate with "ps aux | grep react-native", kill -9 all process and run "react-native run-android/run-ios" again.
